import { HttpStatus } from '@nestjs/common';
import { BaseError } from './base.error';

export enum ErrorCode {
  // Authentication & Authorization
  INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  UNAUTHORIZED_ACCESS = 'AUTH_UNAUTHORIZED_ACCESS',
  TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',

  // User Management
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_USER_DATA = 'USER_INVALID_DATA',
  PASSWORD_TOO_WEAK = 'USER_PASSWORD_TOO_WEAK',

  // Image Management
  IMAGE_NOT_FOUND = 'IMAGE_NOT_FOUND',
  IMAGE_GENERATION_FAILED = 'IMAGE_GENERATION_FAILED',
  IMAGE_UPLOAD_FAILED = 'IMAGE_UPLOAD_FAILED',
  INVALID_IMAGE_FORMAT = 'IMAGE_INVALID_FORMAT',
  IMAGE_SIZE_EXCEEDED = 'IMAGE_SIZE_EXCEEDED',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',

  // System Errors
  DATABASE_ERROR = 'SYSTEM_DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR = 'SYSTEM_EXTERNAL_SERVICE_ERROR',
  VALIDATION_ERROR = 'SYSTEM_VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR = 'SYSTEM_INTERNAL_SERVER_ERROR',

  // File Operations
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
  FILE_DELETE_FAILED = 'FILE_DELETE_FAILED',
  INVALID_FILE_TYPE = 'FILE_INVALID_TYPE',

  // Credit System
  INSUFFICIENT_CREDITS = 'CREDIT_INSUFFICIENT_CREDITS',
}

export class BusinessError extends BaseError {
  constructor(
    code: ErrorCode,
    message: string,
    statusCode: number = HttpStatus.BAD_REQUEST,
    context?: Record<string, any>,
  ) {
    super({ code, message, statusCode, context });
  }
}
